### ISSUE TITLE
Infer a table schema descriptor from a supplied sample of data

### ISSUE THREAD

**Issue by loleg** [frictionlessdata/tableschema-jl#9]
As in the [Python implementation](https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/infer.py), it should be possible to generate a Table Schema object from a tabular data sample.

This is being worked on in https://github.com/loleg/tableschema-jl/tree/schema-validate

**Comment by loleg** [comment]
@roll during `infer`, if there is a mismatch in a column, the first guessed type should be kept as far as I can tell. Is there a need to notify the user in some way, e.g. a console message or some key in the `field`?

**Comment by roll** [comment]
@loleg 
It depends on the inferring strategy e.g.:
- `tablebleschema-js` uses a threshold to decide is type is guessed or not. For example, if threshold is 80% than type inferring will stop if 8 of 10 values have the same type
- `tableschema-py` uses the full scan and all the sample values should be compliant with the guessed type (if I understand it correctly). So it's often 
But none of those methodologies rely on the first guess.

**Comment by loleg** [comment]
@roll okay, it seems to me that `tableschema-py` takes the most occurring match by count as per https://github.com/frictionlessdata/tableschema-py/blob/537796f034b61f8007c1c9bbc4df18fe25b6e3b8/tableschema/schema.py#L294 - I will adopt this strategy as well, unless you prefer thresholding?

**Comment by roll** [comment]
@loleg 
I prefer a thresholding approach like this - https://github.com/frictionlessdata/tableschema-js/blob/master/src/schema.js#L179

If you take a look at what's happening in the Python version in the worst cast scenario e.g. for 1000 rows, 20 columns sample, 95% string - there will be `1000 rows x 20 columns x 10-15 types` very costly `field.cast_value` operations. We had to experience major performance problems for example in `goodtables` runs because of it.

The idea behind probabilistic inferring methodolody that you could stop e.g. if first 19 of 20 column values are strings. So the same file will be inferred in milliseconds.

**Comment by loleg** [comment]
I've added #15 to address your improvement idea @roll - closing this issue since the basic functionality is in place.
